version: "3.8"

services:
  skill-tracking-app:
    container_name: skill-tracking-app
    build:
      args:
        - version=${NODE_VERSION}
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app
    env_file:
      - ./.env
    tty: true